# Generated by Django 5.2.1 on 2025-06-06 04:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotels", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="hotel_email",
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="hotel",
            name="hotel_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
