# Generated by Django 5.2.1 on 2025-08-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotels", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
