# Generated by Django 5.2.1 on 2025-06-07 19:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotels", "0003_hotel_hotel_email_hotel_hotel_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="price_per_hour",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
