# Generated by Django 5.2.1 on 2025-09-09 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotels", "0003_hotel_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="state",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="hotel",
            name="suburb",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="image",
            field=models.ImageField(
                blank=True,
                default="images/default_hotel.webp",
                null=True,
                upload_to="hotels/images/",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="image",
            field=models.ImageField(
                blank=True,
                default="images/default_room.webp",
                null=True,
                upload_to="rooms/images/",
            ),
        ),
    ]
