# Generated by Django 5.2.1 on 2025-09-09 19:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hotels", "0004_hotel_state_hotel_suburb_alter_hotel_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hotel",
            name="state",
        ),
    ]
