# Generated by Django 5.2.1 on 2025-09-20 08:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotels", "0005_remove_hotel_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="price_12_hour",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Discounted price for 12 hours (optional)",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="price_24_hour",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Discounted price for 24 hours (optional)",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
