# Generated by Django 5.2.1 on 2025-07-14 12:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0008_remove_booking_extras"),
        ("hotels", "0005_extra"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Extra",
        ),
    ]
