# Generated by Django 5.2.1 on 2025-09-20 09:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hotels", "0006_room_price_12_hour_room_price_24_hour"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="price_12_hour",
        ),
        migrations.RemoveField(
            model_name="room",
            name="price_24_hour",
        ),
    ]
