# Generated by Django 5.2.1 on 2025-07-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotels", "0007_extraservice"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="account_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="hotel",
            name="account_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="hotel",
            name="bank_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
