# Generated by Django 5.2.1 on 2025-09-20 12:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotels", "0007_remove_room_price_12_hour_remove_room_price_24_hour"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="twelve_hour_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="twenty_four_hour_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
