# Generated by Django 5.2.1 on 2025-09-26 18:16

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotels", "0008_room_twelve_hour_price_room_twenty_four_hour_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("review_text", models.TextField()),
                (
                    "rating",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_approved", models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name="review",
            name="hotel",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="hotels.hotel",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="twelve_hour_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Discounted price for 12 hours (optional)",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="twenty_four_hour_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Discounted price for 24 hours (optional)",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
