# Generated by Django 5.2.1 on 2025-09-26 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotels", "0009_appfeedback_review_hotel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
