# Generated by Django 5.2.1 on 2025-09-27 13:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hotels", "0011_alter_review_options_review_customer_review_user_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="review",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="review",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="review",
            name="user",
        ),
    ]
