# Generated by Django 5.2.1 on 2025-09-30 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotels", "0013_hotelimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotelimage",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="hotels/images/%Y/%m/%d/%(hotel_slug)s/",
            ),
        ),
    ]
