# Generated by Django 5.2.1 on 2025-09-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotels", "0014_alter_hotelimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotel",
            name="image",
            field=models.ImageField(
                blank=True,
                default="images/default_hotel.webp",
                null=True,
                upload_to="hotels/images/default/",
            ),
        ),
        migrations.AlterField(
            model_name="hotelimage",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="hotels/images/default/"
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="image",
            field=models.ImageField(
                blank=True,
                default="images/default_room.webp",
                null=True,
                upload_to="hotels/rooms/images/default/",
            ),
        ),
    ]
