# Generated by Django 5.2.1 on 2025-09-30 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotels", "0015_alter_hotel_image_alter_hotelimage_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Amenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "icon_class",
                    models.CharField(
                        blank=True,
                        help_text="Font Awesome class, e.g., 'fa-solid fa-wifi'",
                        max_length=100,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="hotel",
            name="amenities",
            field=models.ManyToManyField(
                blank=True, related_name="hotels", to="hotels.amenity"
            ),
        ),
    ]
