# Generated by Django 5.2.1 on 2025-09-30 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotels", "0016_amenity_hotel_amenities"),
    ]

    operations = [
        migrations.CreateModel(
            name="HotelPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "policy_text",
                    models.TextField(
                        help_text="Enter the policy rule, e.g., 'Check-in: 2:00 PM'",
                        max_length=500,
                    ),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policies",
                        to="hotels.hotel",
                    ),
                ),
            ],
        ),
    ]
