# Generated by Django 5.2.1 on 2025-10-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotels", "0017_hotelpolicy"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="total_units",
            field=models.PositiveIntegerField(
                default=1, help_text="Number of physical rooms for this category"
            ),
        ),
    ]
