# Generated by Django 5.2.1 on 2025-11-07 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotels", "0018_room_total_units"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="blackout_end",
            field=models.TimeField(
                blank=True,
                help_text="End of blackout (e.g. 06:00). Supports overnight (e.g. 22:00 → 06:00).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="hotel",
            name="blackout_start",
            field=models.TimeField(
                blank=True,
                help_text="Start of blackout (e.g. 22:00). App bookings blocked during this window.",
                null=True,
            ),
        ),
    ]
