# Generated by Django 5.2.1 on 2025-11-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotels", "0019_hotel_blackout_end_hotel_blackout_start"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="duration_mode",
            field=models.CharField(
                choices=[
                    ("all", "All Durations Available"),
                    ("12_only", "12-Hour Bookings Only"),
                    ("24_only", "24-Hour Bookings Only"),
                    ("12_and_24", "12-Hour and 24-Hour Only"),
                ],
                default="all",
                help_text="Control which booking durations guests can select",
                max_length=20,
            ),
        ),
    ]
