# Generated by Django 5.2.1 on 2025-11-09 11:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotels", "0020_hotel_duration_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="price_per_hour",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Hourly rate (required only if offering 3, 6, 9 hour bookings)",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="twelve_hour_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Fixed price for 12-hour booking",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="twenty_four_hour_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Fixed price for 24-hour booking",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
