# Generated by Django 5.2.1 on 2025-11-13 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("hotels", "0021_alter_room_price_per_hour_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PayoutRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payout_reference",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                (
                    "period_start",
                    models.DateField(
                        help_text="Start date of booking period (inclusive)"
                    ),
                ),
                (
                    "period_end",
                    models.DateField(
                        help_text="End date of booking period (inclusive)"
                    ),
                ),
                (
                    "gross_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total revenue (room + extras - discounts) before commission",
                        max_digits=12,
                    ),
                ),
                (
                    "commission_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Platform commission (10% of gross revenue)",
                        max_digits=12,
                    ),
                ),
                (
                    "net_payout",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount actually paid to hotel (90% of gross revenue)",
                        max_digits=12,
                    ),
                ),
                ("booking_count", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved - Ready to Pay"),
                            ("processing", "Processing Payment"),
                            ("completed", "Payment Completed"),
                            ("failed", "Payment Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "paystack_transfer_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("paystack_response", models.JSONField(blank=True, null=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Internal notes about this payout"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_payouts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payouts",
                        to="hotels.hotel",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["hotel", "status"],
                        name="superadmin__hotel_i_24693e_idx",
                    ),
                    models.Index(
                        fields=["period_start", "period_end"],
                        name="superadmin__period__1e5813_idx",
                    ),
                ],
            },
        ),
    ]
