# Generated by Django 5.2.1 on 2025-08-09 15:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("full_name", models.CharField(blank=True, max_length=255)),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                ("is_active", models.BooleanField(default=False)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("loyalty_points", models.IntegerField(default=0)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LoyaltyRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "points_per_percent",
                    models.IntegerField(
                        default=100, help_text="Points required for 1% discount"
                    ),
                ),
                (
                    "max_discount_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=100,
                        help_text="Maximum discount percentage (e.g., 100 for 100%)",
                        max_digits=5,
                    ),
                ),
                (
                    "min_points_to_use",
                    models.IntegerField(
                        default=100,
                        help_text="Minimum points required to use loyalty discount",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
            ],
        ),
    ]
