# Generated by Django 5.2.1 on 2025-10-31 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0002_customer_username"),
        ("hotels", "0018_room_total_units"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="favorite_hotels",
            field=models.ManyToManyField(
                blank=True,
                help_text="Hotels this customer has favorited",
                related_name="favorited_by",
                to="hotels.hotel",
            ),
        ),
    ]
