# Generated by Django 5.2.1 on 2025-11-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0003_alter_booking_total_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="hotel_revenue_snapshot",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Hotel's revenue at time of booking (room cost + extras, frozen)",
                max_digits=10,
            ),
        ),
    ]
