# Generated by Django 5.2.1 on 2025-06-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0004_booking_service_charge_booking_total_amount_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingDuration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hours",
                    models.PositiveIntegerField(
                        help_text="Duration in hours (e.g., 3, 6, 9)", unique=True
                    ),
                ),
            ],
            options={
                "ordering": ["hours"],
            },
        ),
    ]
