# Generated by Django 5.2.1 on 2025-06-11 01:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0005_bookingduration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="booking_reference",
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
    ]
