# Generated by Django 5.2.1 on 2025-07-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0006_alter_booking_booking_reference"),
        ("hotels", "0005_extra"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="extras",
            field=models.ManyToManyField(blank=True, to="hotels.extra"),
        ),
    ]
