# Generated by Django 5.2.1 on 2025-07-14 12:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0007_booking_extras"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="extras",
        ),
    ]
