# Generated by Django 5.2.1 on 2025-07-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0008_remove_booking_extras"),
        ("hotels", "0007_extraservice"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="extras",
            field=models.ManyToManyField(blank=True, to="hotels.extraservice"),
        ),
    ]
